spring:
  output:
    ansi:
      enabled: always
  jackson:
    property-naming-strategy: SNAKE_CASE


  datasource:
    url: jdbc:oracle:thin:@healthdb_high?TNS_ADMIN=/Users/user/Desktop/mwindow/allnew/wallet/Wallet_healthDB
    username: admin
    password: Ab123456789123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug